"""Unified CLI entrypoint for LightRoute training and inference pipelines."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

CURRENT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = CURRENT_DIR.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.pipeline import (  # noqa: E402
    build_indexes_pipeline,
    eval_bm25_retrieval_pipeline,
    eval_docvqa_pipeline,
    eval_adaptive_fusion_pipeline,
    eval_adaptive_fusion_ablate_lex_pipeline,
    eval_adaptive_fusion_ablate_mlp_lex_pipeline,
    eval_adaptive_fusion_ablate_mlp_ocrq_pipeline,
    eval_adaptive_fusion_ablate_mlp_q_pipeline,
    eval_adaptive_fusion_ablate_mlp_pipeline,
    eval_adaptive_fusion_ablate_ocrq_pipeline,
    eval_adaptive_fusion_ablate_q_pipeline,
    eval_adaptive_fusion_best_val_pipeline,
    eval_adaptive_fusion_mlp_ocrq_bge_pipeline,
    eval_adaptive_fusion_mlp_ocrq_chunk_pipeline,
    eval_adaptive_fusion_visual_colqwen_ocr_chunk_val_pipeline,
    eval_adaptive_fusion_mlp_ocrq_chunkplus_pipeline,
    eval_adaptive_fusion_mlp_ocrq_hybrid_pipeline,
    eval_adaptive_fusion_mlp_ocrq_nvchunk_pipeline,
    eval_adaptive_fusion_v2_pipeline,
    eval_ocr_bge_debug_pipeline,
    eval_ocr_bge_chunk_pipeline,
    eval_ocr_bge_chunk_rerank_pipeline,
    eval_ocr_bge_retrieval_pipeline,
    eval_ocr_bge_rerank_debug_pipeline,
    eval_ocr_bge_rerank_pipeline,
    eval_ocr_hybrid_pipeline,
    eval_ocr_jina_chunk_pipeline,
    eval_ocr_nv_chunk_pipeline,
    eval_visual_colqwen_retrieval_pipeline,
    eval_fixed_fusion_pipeline,
    eval_retrieval_pipeline,
    eval_rrf_pipeline,
    eval_visual_retrieval_pipeline,
    infer_bm25_test_pipeline,
    infer_adaptive_fusion_test_pipeline,
    infer_adaptive_fusion_ablate_lex_test_pipeline,
    infer_adaptive_fusion_ablate_mlp_lex_test_pipeline,
    infer_adaptive_fusion_ablate_mlp_ocrq_test_pipeline,
    infer_adaptive_fusion_ablate_mlp_q_test_pipeline,
    infer_adaptive_fusion_ablate_mlp_test_pipeline,
    infer_adaptive_fusion_ablate_ocrq_test_pipeline,
    infer_adaptive_fusion_ablate_q_test_pipeline,
    infer_adaptive_fusion_best_test_pipeline,
    infer_adaptive_fusion_mlp_ocrq_bge_test_pipeline,
    infer_adaptive_fusion_mlp_ocrq_chunk_test_pipeline,
    infer_adaptive_fusion_visual_colqwen_ocr_chunk_test_pipeline,
    infer_adaptive_fusion_mlp_ocrq_chunkplus_test_pipeline,
    infer_adaptive_fusion_mlp_ocrq_hybrid_test_pipeline,
    infer_adaptive_fusion_mlp_ocrq_nvchunk_test_pipeline,
    infer_adaptive_fusion_v2_test_pipeline,
    infer_docvqa_pipeline,
    infer_ocr_bge_rerank_test_pipeline,
    infer_ocr_bge_test_pipeline,
    infer_ocr_bge_chunk_rerank_test_pipeline,
    infer_ocr_bge_chunk_test_pipeline,
    infer_ocr_hybrid_test_pipeline,
    infer_ocr_jina_chunk_test_pipeline,
    infer_ocr_nv_chunk_test_pipeline,
    infer_visual_colqwen_test_pipeline,
    infer_fixed_fusion_test_pipeline,
    infer_rrf_test_pipeline,
    infer_visual_test_pipeline,
    prepare_data_pipeline,
    train_adaptive_fusion_pipeline,
    train_adaptive_fusion_ablate_lex_pipeline,
    train_adaptive_fusion_ablate_mlp_lex_pipeline,
    train_adaptive_fusion_ablate_mlp_ocrq_pipeline,
    train_adaptive_fusion_ablate_mlp_q_pipeline,
    train_adaptive_fusion_ablate_mlp_pipeline,
    train_adaptive_fusion_ablate_ocrq_pipeline,
    train_adaptive_fusion_ablate_q_pipeline,
    train_adaptive_fusion_best_pipeline,
    train_adaptive_fusion_mlp_ocrq_bge_pipeline,
    train_adaptive_fusion_mlp_ocrq_chunk_pipeline,
    train_adaptive_fusion_visual_colqwen_ocr_chunk_pipeline,
    train_adaptive_fusion_mlp_ocrq_chunkplus_pipeline,
    train_adaptive_fusion_mlp_ocrq_hybrid_pipeline,
    train_adaptive_fusion_mlp_ocrq_nvchunk_pipeline,
    train_adaptive_fusion_v2_pipeline,
    train_fusion_pipeline,
)
from src.utils.config_utils import load_config  # noqa: E402


def parse_args() -> argparse.Namespace:
    """Parse command line arguments for the unified project entrypoint."""
    parser = argparse.ArgumentParser(description="LightRoute DocVQA pipeline")
    parser.add_argument("--config", default="configs/base.yaml", help="Path to the base YAML config.")
    parser.add_argument(
        "--device",
        default=None,
        help="Optional device override, e.g. cpu, cuda, cuda:0, cuda:1.",
    )
    parser.add_argument(
        "--max-train-samples",
        type=int,
        default=None,
        help="Optional cap for train split size, useful for smoke testing.",
    )
    parser.add_argument(
        "--max-val-samples",
        type=int,
        default=None,
        help="Optional cap for val split size, useful for smoke testing.",
    )
    parser.add_argument(
        "--mode",
        default="eval_retrieval",
        choices=[
            "prepare_data",
            "build_indexes",
            "eval_retrieval",
            "eval_bm25_val",
            "eval_ocr_bge_val",
            "eval_ocr_bge_debug_val",
            "eval_ocr_bge_rerank_val",
            "eval_ocr_bge_rerank_debug_val",
            "eval_ocr_bge_chunk_val",
            "eval_ocr_bge_chunk_rerank_val",
            "eval_ocr_hybrid_val",
            "eval_ocr_jina_chunk_val",
            "eval_ocr_nv_chunk_val",
            "eval_visual_val",
            "eval_visual_colqwen_val",
            "eval_fixed_fusion_val",
            "eval_rrf_val",
            "train_adaptive_fusion",
            "train_adaptive_fusion_ablate_q",
            "train_adaptive_fusion_ablate_ocrq",
            "train_adaptive_fusion_ablate_lex",
            "train_adaptive_fusion_ablate_mlp",
            "train_adaptive_fusion_ablate_mlp_q",
            "train_adaptive_fusion_ablate_mlp_ocrq",
            "train_adaptive_fusion_ablate_mlp_lex",
            "train_adaptive_fusion_best",
            "train_adaptive_fusion_mlp_ocrq_bge",
            "train_adaptive_fusion_mlp_ocrq_chunk",
            "train_adaptive_fusion_visual_colqwen_ocr_chunk",
            "train_adaptive_fusion_mlp_ocrq_chunkplus",
            "train_adaptive_fusion_mlp_ocrq_hybrid",
            "train_adaptive_fusion_mlp_ocrq_nvchunk",
            "train_adaptive_fusion_v2",
            "eval_adaptive_fusion_val",
            "eval_adaptive_fusion_ablate_q_val",
            "eval_adaptive_fusion_ablate_ocrq_val",
            "eval_adaptive_fusion_ablate_lex_val",
            "eval_adaptive_fusion_ablate_mlp_val",
            "eval_adaptive_fusion_ablate_mlp_q_val",
            "eval_adaptive_fusion_ablate_mlp_ocrq_val",
            "eval_adaptive_fusion_ablate_mlp_lex_val",
            "eval_adaptive_fusion_best_val",
            "eval_adaptive_fusion_mlp_ocrq_bge_val",
            "eval_adaptive_fusion_mlp_ocrq_chunk_val",
            "eval_adaptive_fusion_visual_colqwen_ocr_chunk_val",
            "eval_adaptive_fusion_mlp_ocrq_chunkplus_val",
            "eval_adaptive_fusion_mlp_ocrq_hybrid_val",
            "eval_adaptive_fusion_mlp_ocrq_nvchunk_val",
            "eval_adaptive_fusion_v2_val",
            "infer_bm25_test",
            "infer_ocr_bge_test",
            "infer_ocr_bge_rerank_test",
            "infer_ocr_bge_chunk_test",
            "infer_ocr_bge_chunk_rerank_test",
            "infer_ocr_hybrid_test",
            "infer_ocr_jina_chunk_test",
            "infer_ocr_nv_chunk_test",
            "infer_visual_test",
            "infer_visual_colqwen_test",
            "infer_fixed_fusion_test",
            "infer_rrf_test",
            "infer_adaptive_fusion_test",
            "infer_adaptive_fusion_ablate_q_test",
            "infer_adaptive_fusion_ablate_ocrq_test",
            "infer_adaptive_fusion_ablate_lex_test",
            "infer_adaptive_fusion_ablate_mlp_test",
            "infer_adaptive_fusion_ablate_mlp_q_test",
            "infer_adaptive_fusion_ablate_mlp_ocrq_test",
            "infer_adaptive_fusion_ablate_mlp_lex_test",
            "infer_adaptive_fusion_best_test",
            "infer_adaptive_fusion_mlp_ocrq_bge_test",
            "infer_adaptive_fusion_mlp_ocrq_chunk_test",
            "infer_adaptive_fusion_visual_colqwen_ocr_chunk_test",
            "infer_adaptive_fusion_mlp_ocrq_chunkplus_test",
            "infer_adaptive_fusion_mlp_ocrq_hybrid_test",
            "infer_adaptive_fusion_mlp_ocrq_nvchunk_test",
            "infer_adaptive_fusion_v2_test",
            "train_fusion",
            "infer_docvqa",
            "eval_docvqa",
        ],
        help="Pipeline mode to execute.",
    )
    return parser.parse_args()


def main() -> None:
    """Load configuration and dispatch to the selected pipeline."""
    args = parse_args()
    cfg = load_config(args.config)
    if args.device:
        cfg.device = args.device
        if hasattr(cfg, "visual"):
            cfg.visual.device = args.device
        if hasattr(cfg, "ocr_retrieval"):
            cfg.ocr_retrieval.device = args.device
        if hasattr(cfg, "ocr_nv_retrieval"):
            cfg.ocr_nv_retrieval.device = args.device
        if hasattr(cfg, "ocr_jina_retrieval"):
            cfg.ocr_jina_retrieval.device = args.device
        if hasattr(cfg, "visual_colqwen_retrieval"):
            cfg.visual_colqwen_retrieval.device = args.device
    if args.max_train_samples is not None:
        cfg.training.max_train_samples = int(args.max_train_samples)
    if args.max_val_samples is not None:
        cfg.training.max_val_samples = int(args.max_val_samples)
    dispatch = {
        "prepare_data": prepare_data_pipeline,
        "build_indexes": build_indexes_pipeline,
        "eval_retrieval": eval_retrieval_pipeline,
        "eval_bm25_val": eval_bm25_retrieval_pipeline,
        "eval_ocr_bge_val": eval_ocr_bge_retrieval_pipeline,
        "eval_ocr_bge_debug_val": eval_ocr_bge_debug_pipeline,
        "eval_ocr_bge_rerank_val": eval_ocr_bge_rerank_pipeline,
        "eval_ocr_bge_rerank_debug_val": eval_ocr_bge_rerank_debug_pipeline,
        "eval_ocr_bge_chunk_val": eval_ocr_bge_chunk_pipeline,
        "eval_ocr_bge_chunk_rerank_val": eval_ocr_bge_chunk_rerank_pipeline,
        "eval_ocr_hybrid_val": eval_ocr_hybrid_pipeline,
        "eval_ocr_jina_chunk_val": eval_ocr_jina_chunk_pipeline,
        "eval_ocr_nv_chunk_val": eval_ocr_nv_chunk_pipeline,
        "eval_visual_val": eval_visual_retrieval_pipeline,
        "eval_visual_colqwen_val": eval_visual_colqwen_retrieval_pipeline,
        "eval_fixed_fusion_val": eval_fixed_fusion_pipeline,
        "eval_rrf_val": eval_rrf_pipeline,
        "train_adaptive_fusion": train_adaptive_fusion_pipeline,
        "train_adaptive_fusion_ablate_q": train_adaptive_fusion_ablate_q_pipeline,
        "train_adaptive_fusion_ablate_ocrq": train_adaptive_fusion_ablate_ocrq_pipeline,
        "train_adaptive_fusion_ablate_lex": train_adaptive_fusion_ablate_lex_pipeline,
        "train_adaptive_fusion_ablate_mlp": train_adaptive_fusion_ablate_mlp_pipeline,
        "train_adaptive_fusion_ablate_mlp_q": train_adaptive_fusion_ablate_mlp_q_pipeline,
        "train_adaptive_fusion_ablate_mlp_ocrq": train_adaptive_fusion_ablate_mlp_ocrq_pipeline,
        "train_adaptive_fusion_ablate_mlp_lex": train_adaptive_fusion_ablate_mlp_lex_pipeline,
        "train_adaptive_fusion_best": train_adaptive_fusion_best_pipeline,
        "train_adaptive_fusion_mlp_ocrq_bge": train_adaptive_fusion_mlp_ocrq_bge_pipeline,
        "train_adaptive_fusion_mlp_ocrq_chunk": train_adaptive_fusion_mlp_ocrq_chunk_pipeline,
        "train_adaptive_fusion_visual_colqwen_ocr_chunk": train_adaptive_fusion_visual_colqwen_ocr_chunk_pipeline,
        "train_adaptive_fusion_mlp_ocrq_chunkplus": train_adaptive_fusion_mlp_ocrq_chunkplus_pipeline,
        "train_adaptive_fusion_mlp_ocrq_hybrid": train_adaptive_fusion_mlp_ocrq_hybrid_pipeline,
        "train_adaptive_fusion_mlp_ocrq_nvchunk": train_adaptive_fusion_mlp_ocrq_nvchunk_pipeline,
        "train_adaptive_fusion_v2": train_adaptive_fusion_v2_pipeline,
        "eval_adaptive_fusion_val": eval_adaptive_fusion_pipeline,
        "eval_adaptive_fusion_ablate_q_val": eval_adaptive_fusion_ablate_q_pipeline,
        "eval_adaptive_fusion_ablate_ocrq_val": eval_adaptive_fusion_ablate_ocrq_pipeline,
        "eval_adaptive_fusion_ablate_lex_val": eval_adaptive_fusion_ablate_lex_pipeline,
        "eval_adaptive_fusion_ablate_mlp_val": eval_adaptive_fusion_ablate_mlp_pipeline,
        "eval_adaptive_fusion_ablate_mlp_q_val": eval_adaptive_fusion_ablate_mlp_q_pipeline,
        "eval_adaptive_fusion_ablate_mlp_ocrq_val": eval_adaptive_fusion_ablate_mlp_ocrq_pipeline,
        "eval_adaptive_fusion_ablate_mlp_lex_val": eval_adaptive_fusion_ablate_mlp_lex_pipeline,
        "eval_adaptive_fusion_best_val": eval_adaptive_fusion_best_val_pipeline,
        "eval_adaptive_fusion_mlp_ocrq_bge_val": eval_adaptive_fusion_mlp_ocrq_bge_pipeline,
        "eval_adaptive_fusion_mlp_ocrq_chunk_val": eval_adaptive_fusion_mlp_ocrq_chunk_pipeline,
        "eval_adaptive_fusion_visual_colqwen_ocr_chunk_val": eval_adaptive_fusion_visual_colqwen_ocr_chunk_val_pipeline,
        "eval_adaptive_fusion_mlp_ocrq_chunkplus_val": eval_adaptive_fusion_mlp_ocrq_chunkplus_pipeline,
        "eval_adaptive_fusion_mlp_ocrq_hybrid_val": eval_adaptive_fusion_mlp_ocrq_hybrid_pipeline,
        "eval_adaptive_fusion_mlp_ocrq_nvchunk_val": eval_adaptive_fusion_mlp_ocrq_nvchunk_pipeline,
        "eval_adaptive_fusion_v2_val": eval_adaptive_fusion_v2_pipeline,
        "infer_bm25_test": infer_bm25_test_pipeline,
        "infer_ocr_bge_test": infer_ocr_bge_test_pipeline,
        "infer_ocr_bge_rerank_test": infer_ocr_bge_rerank_test_pipeline,
        "infer_ocr_bge_chunk_test": infer_ocr_bge_chunk_test_pipeline,
        "infer_ocr_bge_chunk_rerank_test": infer_ocr_bge_chunk_rerank_test_pipeline,
        "infer_ocr_hybrid_test": infer_ocr_hybrid_test_pipeline,
        "infer_ocr_jina_chunk_test": infer_ocr_jina_chunk_test_pipeline,
        "infer_ocr_nv_chunk_test": infer_ocr_nv_chunk_test_pipeline,
        "infer_visual_test": infer_visual_test_pipeline,
        "infer_visual_colqwen_test": infer_visual_colqwen_test_pipeline,
        "infer_fixed_fusion_test": infer_fixed_fusion_test_pipeline,
        "infer_rrf_test": infer_rrf_test_pipeline,
        "infer_adaptive_fusion_test": infer_adaptive_fusion_test_pipeline,
        "infer_adaptive_fusion_ablate_q_test": infer_adaptive_fusion_ablate_q_test_pipeline,
        "infer_adaptive_fusion_ablate_ocrq_test": infer_adaptive_fusion_ablate_ocrq_test_pipeline,
        "infer_adaptive_fusion_ablate_lex_test": infer_adaptive_fusion_ablate_lex_test_pipeline,
        "infer_adaptive_fusion_ablate_mlp_test": infer_adaptive_fusion_ablate_mlp_test_pipeline,
        "infer_adaptive_fusion_ablate_mlp_q_test": infer_adaptive_fusion_ablate_mlp_q_test_pipeline,
        "infer_adaptive_fusion_ablate_mlp_ocrq_test": infer_adaptive_fusion_ablate_mlp_ocrq_test_pipeline,
        "infer_adaptive_fusion_ablate_mlp_lex_test": infer_adaptive_fusion_ablate_mlp_lex_test_pipeline,
        "infer_adaptive_fusion_best_test": infer_adaptive_fusion_best_test_pipeline,
        "infer_adaptive_fusion_mlp_ocrq_bge_test": infer_adaptive_fusion_mlp_ocrq_bge_test_pipeline,
        "infer_adaptive_fusion_mlp_ocrq_chunk_test": infer_adaptive_fusion_mlp_ocrq_chunk_test_pipeline,
        "infer_adaptive_fusion_visual_colqwen_ocr_chunk_test": infer_adaptive_fusion_visual_colqwen_ocr_chunk_test_pipeline,
        "infer_adaptive_fusion_mlp_ocrq_chunkplus_test": infer_adaptive_fusion_mlp_ocrq_chunkplus_test_pipeline,
        "infer_adaptive_fusion_mlp_ocrq_hybrid_test": infer_adaptive_fusion_mlp_ocrq_hybrid_test_pipeline,
        "infer_adaptive_fusion_mlp_ocrq_nvchunk_test": infer_adaptive_fusion_mlp_ocrq_nvchunk_test_pipeline,
        "infer_adaptive_fusion_v2_test": infer_adaptive_fusion_v2_test_pipeline,
        "train_fusion": train_fusion_pipeline,
        "infer_docvqa": infer_docvqa_pipeline,
        "eval_docvqa": eval_docvqa_pipeline,
    }
    dispatch[args.mode](cfg)


if __name__ == "__main__":
    main()
